#singletonServer: http://g11n-vip-dev-1.eng.vmware.com:8091
singletonServer: https://g11n-vip-dev-1.eng.vmware.com:8090

enableCache: false
initializeCache: false
#unit: second
cacheExpiredTime: 500


defaultLocale: zh-Hans

localBundles: ""

name: GoClientTest
version: 1.0.0
