singletonServer: https://localhost:8090
#singletonServer: http://localhost:8091

enableCache: false
initializeCache: false
#unit: second
cacheExpiredTime: 500


defaultLocale: zh-Hans

localBundles: ""

name: NonExistingProduct
version: 1.0.0
