coverage:
  precision: 2
  round: down
  range: "75...100"
  status:
    project:
      default:
        branches: g11n-angular-client
        target: 75%
        if_ci_failed: error
        if_not_found: failure
    patch:
      default:
        branches: g11n-angular-client
        target: 0%
        if_ci_failed: error
        if_not_found: failure

