coverage:
  precision: 2        
  round: down         
  range: 75...100    
  status:
    project:                   
      default:                 
        enabled: yes           
        target: 75%                 
        if_no_uploads: error   
        if_not_found: failure  
        if_ci_failed: error   
    patch:
      default:
        enabled: true            
        target: 75%                      
        if_no_uploads: error     
        if_not_found: failure
        if_ci_failed: error