singletonServer: ""

enableCache: false
initializeCache: false
#unit: second
cacheExpiredTime: 1


defaultLocale: zh-Hans

localBundles: "../testdata/localBundles/GoClientTest/"


name: NonExistentProduct
version: 1.0.0
