dist: trusty
language: node_js
node_js:
  - "10"
python:
  - 3.4
before_install:
- |
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '\.md$' || {
      echo "Only docs were updated, stopping build process."
      exit
    }
    export CHROME_BIN=chromium-browser
    sudo apt-get -y install unzip
    sudo apt-get -y install wget
    sudo apt-get -y install python3-pip python-dev
    python3 -V
    pip3 -V
install:
  - sudo pip3 install requests
jobs:
  include:
  - name: "Check Header"
    env: TEST=check_header
  - name: "Unit Test"
    env: TEST=unit_test
  - name: "Code Scan"
    env: TEST=code_scan
script: >
  if [ x${TEST} = xcheck_header ]; then
    git clone --branch=devops https://github.com/vmware/singleton.git devops
    cp $TRAVIS_BUILD_DIR/devops/check_headers.py .
    chmod +x check_headers.py
    python3 ./check_headers.py -f "$(git diff --name-only --diff-filter=d $TRAVIS_COMMIT_RANGE)"
  fi &&
  if [ x${TEST} = xunit_test ]; then
    sed -i "s/'Chrome'/'ChromeHeadless'/g" projects/angular-client/karma.conf.js && cat projects/angular-client/karma.conf.js
    npm install --registry https://registry.npmjs.org
    npm run test
  fi &&
  if [ x${TEST} = xcode_scan ]; then
    SONARSCANNER='sonar-scanner-cli-4.0.0.1744-linux'
    SONARSCANNERINNER='sonar-scanner-4.0.0.1744-linux'
    npm install npm
    npm install tslint
    npm install typescript
    tsc -v
    wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/$SONARSCANNER.zip
    unzip $SONARSCANNER.zip
    rm -f $SONARSCANNER.zip
    mkdir -p g11n-angular-client
    shopt -s extglob
    mv !($SONARSCANNERINNER|g11n-angular-client) g11n-angular-client/
    git clone --branch=devops https://github.com/vmware/singleton.git devops
    cp -a devops/sonar/* .
    rm -rf devops
    cd g11n-angular-client
    sed -i "s/'Chrome'/'ChromeHeadless'/g" projects/angular-client/karma.conf.js && cat projects/angular-client/karma.conf.js
    npm install --registry https://registry.npmjs.org
    str=$(printf '=%.0s' {1..50})
    echo $str Unit Test Start $str
    npm run test
    echo $str Unit Test End $str
    cd ..
    ls -al g11n-angular-client/coverage/angular-client
    echo $str Code Scan Start $str
    python ./config_sonar_project.py -ProjectName $SONAR_ORG-singleton-angular-client-$TRAVIS_BRANCH -ProjectKey $SONAR_ORG-singleton-angular-client-$TRAVIS_BRANCH -OrgKey $SONAR_ORG -QualityGateName angular-client-gate -QualityGateConditions ./quality_gates/angular-client.json -SonarToken $SONAR_TOKEN
    ./$SONARSCANNERINNER/bin/sonar-scanner -Dsonar.sources=./g11n-angular-client -Dsonar.exclusions=**/node_modules/**/*,**/sample/**/*,**/*.js,**/*.d.ts,**/coverage/**/*,**/test.ts -Dsonar.projectName=$SONAR_ORG-singleton-angular-client-$TRAVIS_BRANCH -Dsonar.branch.name=master -Dsonar.projectKey=$SONAR_ORG-singleton-angular-client-$TRAVIS_BRANCH -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORG -Dsonar.login=$SONAR_TOKEN -Dsonar.javascript.lcov.reportPaths="./g11n-angular-client/coverage/angular-client/lcov.info"  -Dsonar.typescript.lcov.reportPaths="./g11n-angular-client/coverage/angular-client/lcov.info" -Dsonar.c.file.suffixes=- -Dsonar.cpp.file.suffixes=- -Dsonar.objc.file.suffixes=-
    echo $str Code Scan End $str
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '\.travis\.yml$' || {
      echo "No need to check sonar quality gate for only travis configuration updates"
      exit
    }
    sleep 5 && python3 ./check_sonar_qualitygate.py -ProjectKeyPrefixArray=$SONAR_ORG-singleton-angular-client-$TRAVIS_BRANCH -HostName=https://sonarcloud.io
  fi
