#singletonServer: https://g11n-vip-dev-1.eng.vmware.com:8090
singletonServer: ""

enableCache: true
initializeCache: true
#unit: second
cacheExpiredTime: 0


defaultLocale: zh-Hans

localBundles: "../testdata/localBundles/GoClientTest/1.0.0"

name: GoClientTest
version: 1.0.0