name: Singleton Ruby Client

on:
  push:
    paths:
    - '.github/workflows/ruby.yml'
    - 'g11n-ruby-client/**'
    - 'server/**'
  pull_request:
    paths: 
    - '.github/workflows/ruby.yml'
    - 'g11n-ruby-client/**'
    - 'server/**'
  
defaults:
  run:
    working-directory: g11n-ruby-client
    
jobs:
  pre-process:
    name: Pre-process
    uses: aleksbogdanov12/singleton-monorepo/.github/workflows/pre-process.yml@devops

  check-header:
    name: Check Header
    needs: pre-process
    if: needs.pre-process.outputs.were-only-docs-updated != 'yes'
    uses: aleksbogdanov12/singleton-monorepo/.github/workflows/check.yml@devops

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: pre-process
    if: needs.pre-process.outputs.were-only-docs-updated != 'yes'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: g11n-ruby-client
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Install dependencies
        run: bundle install
      - name: Unit test
        run: |
          COVERAGE=true bundle exec rspec
      - name: Upload Codecov report for ruby-client
        uses: codecov/codecov-action@v2
        with:
          files: coverage/coverage.json
          flags: g11n-ruby-client

  security-analysis:
    name: Security Analysis
    runs-on: ubuntu-latest
    needs: pre-process
    if: needs.pre-process.outputs.were-only-docs-updated != 'yes'
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Install dependencies
        run: bundle install
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ruby
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    if: needs.pre-process.outputs.were-only-docs-updated != 'yes'
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master  
        with:
          output: results.sarif
          format: sarif
          # Adjust severity of non-security issues
          gh-code-scanning-compat: true
          # Force 0 exit code to allow SARIF file generation
          # This will handover control about PR rejection to the GitHub side
          max-allowed-issues: 2147483647  
      # Upload the SARIF file generated in the previous step  
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: results.sarif

  smoke-test:
    name: Smoke Test
    runs-on: ubuntu-latest
    needs: pre-process
    if: needs.pre-process.outputs.were-only-docs-updated != 'yes'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: server
                           g11n-ruby-client
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Install dependencies
        run: bundle install
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Smoke Test
        run: |
          export PATH=${PATH/:\/usr\/local\/lib\/jvm\/openjdk11\/bin:/:}
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk
          export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
          git clone --branch=devops --depth= 1https://github.com/vmware/singleton.git devops
          cd $GITHUB_WORKSPACE/server/g11n-ws && ./gradlew build -x test
          cp $GITHUB_WORKSPACE/g11n-ruby-client/devops/deploy/i18n-service/Dockerfile $GITHUB_WORKSPACE/server/publish/
          cd $GITHUB_WORKSPACE/server/publish && mv singleton-[0~9]*.jar i18n-service.jar
          docker build -t singleton .
          docker run -d -p 8090:8090 -p 8091:8091 --name singleton singleton
          docker ps
          sleep 15s
          mkdir -p $GITHUB_WORKSPACE/l10n/bundles
          cp -r $GITHUB_WORKSPACE/g11n-ruby-client/devops/autotest/client/ruby/l10n/bundles $GITHUB_WORKSPACE/l10n/
          docker cp $GITHUB_WORKSPACE/l10n singleton:/
          cd $GITHUB_WORKSPACE
          cp -r $GITHUB_WORKSPACE/devops/autotest/client/ruby/l10n/bundles/* $GITHUB_WORKSPACE/l10n/bundles
          cd $GITHUB_WORKSPACE/devops/autotest/client/ruby
          sed -i 's|path => "../../../../ruby_client/singleton|path => "/home/runner/work/singleton/singleton|g' Gemfile
          bundle install
          bundle exec rspec spec
